title: Pinxian Zeng's Homepage
page-top-title: Pinxian Zeng
top-section-bg-text: Pinxian Zeng's Page
home-subtitle: Pinxian Zeng's Page&ensp;|&ensp;曾品闲
copyright-text: '&copy; Sen Li 2023-2026. All Rights Reserved.'
