title: Aru's Footprints
page-top-title: Just a Beginner of ML/CV
top-section-bg-text: Aru's Footprints
home-subtitle: Pinxian Zeng &ensp;|&ensp;曾品闲
copyright-text: '&copy; Sen Li 2023-2026. All Rights Reserved.'
